<a href="https://colab.research.google.com/github/JagdishChavan081/Machine_Learning/blob/master/Python%20for%20machine%20Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#initializing numpy array with same number
n1 = np.full((2,2),10)

In [3]:
n1

array([[10, 10],
       [10, 10]])

In [4]:
 n5 = np.full((3,3),(5))
 n5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [5]:
n6 = np.full((3,6),(9))
n6

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [6]:
n1 = np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
n1 = np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
n1 = np.arange(10,51)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
n2 = np.arange(1,105,10)
n2

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101])

In [10]:
#initialize Numpy array with random numbers
import numpy as np
n1 = np.random.randint(1,100,5)
n1

array([28, 77, 89,  1, 86])

In [11]:
n5 = np.random.randint(100,1000,10)
n5

array([580, 597, 515, 657, 780, 399, 615, 661, 136, 886])

In [12]:
#checking the shape of Numpy arrays
n1 = np.array([[1,2,3],[4,5,6]])
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
n1.shape

(2, 3)

In [14]:
n1.shape = (3,2)
n1.shape

(3, 2)

In [15]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
n1 = np.array([[1,2,3],[4,5,6]])

In [17]:
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
n1.shape

(2, 3)

In [19]:
n1.shape = (3,2)

In [20]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
#joining Numpy Arrays
#vstack(vertical stack)

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.vstack((n1,n2))


array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
#hstack(horizantal Stack)
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [23]:
#column stack
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [24]:
  #NUMPY INTERSECTION AND DIFFERENCE
  n1 = np.array([10,20,30,40,50,60])
  n2 = np.array([50,60,70,80,90])

  #intersect1d --> use to find comman value in given array
  np.intersect1d(n1,n2)

array([50, 60])

In [25]:
#setdiff1d--> shows element which are diff
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [26]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [27]:
#NumpyArray MAthematics
#Addition of Numpy Array
n1 = np.array([10,20])
n2 = np.array([30,40])

np.sum([n1,n2])

100

In [28]:
np.sum([n1,n2],axis = 0)

array([40, 60])

In [29]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [30]:
#basic numy array mathematics
#baic addition
n1 = np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [31]:
#basic multiplication
n1 = np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [32]:
#basic substraction
n1 = np.array([10,20,30])
n1=n1-1
n1

array([ 9, 19, 29])

In [33]:
#basic devision
n1=n1/2
n1

array([ 4.5,  9.5, 14.5])

In [34]:
#numpy baic math function
#mean
n1=np.array([10,20,30,40,50,60])
np.mean(n1)

35.0

In [35]:
#standard deviation
n1 = np.array([1,5,3,100,4,48])
np.std(n1)

36.59424666377065

In [36]:
#Median
import numpy as np
n1 = np.array([11,44,5,96,67,85])
np.median(n1)

55.5

In [37]:
#Saving and Loading Numpy Array
#saving numpy array
import numpy as np
n1 = np.array([10,20,30,40,50,60])
np.save('my_numpy',n1)

In [38]:
#Loading numpy array
n2 = np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60])

#Intro To Pandas

Pandas stand for Panel Data and is the core library for data manupulation and data analysis.


consist of single and multi-dimenshional data structure for data manipulation

single-dimentional --> Series object

Multi-dimentional --> Data-frame

In [39]:
#Series Object is one-dimenshional labled array

import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [40]:
type(s1)

pandas.core.series.Series

In [41]:
#changing Index
import pandas as pd
s1 = pd.Series([1,2,3,4,5],index =['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [42]:
#Series object form Dictonary
import pandas as pd
pd.Series({'a':10,'b':20,'c':30})

a    10
b    20
c    30
dtype: int64

In [43]:
#Changing index value of Series
pd.Series({'a':10,'b':20,'c':30},index = ['b','c','d','a'])

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64

In [44]:
#Extracting Individual Elements
#Extacting Single element
s1 =pd.Series([1,2,3,4,5,6,7,8,9])
s1[3]

4

In [45]:
#Extracting elements form back
s1 = pd.Series([1,2,3,4,5,6,7,8,9])
s1[-3:]

6    7
7    8
8    9
dtype: int64

In [46]:
#,Extracting a Sequence of elements
s1 = pd.Series([1,2,3,4,5,6,7,8,9])
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [47]:
#Basic Math Operations on Series
#Adding a Sclar value to Series Elements
s1+5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int64

In [48]:
#Adding two Series Objects
s2 = pd.Series([10,20,30,40,50,60,70,80,90])
s1+s2

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

#Intro To Pandas Dataframe

Dataframe is a 2-dimenshional labbled data-structure

A Data-frame Comprises of rows and columns


In [49]:
 #creating Data frame with Dictonary
 import pandas as pd

 pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,25,92]})

Name  Marks
0   Bob     76
1   Sam     25
2  Anne     92

#Dataframe In-Built Functions

1)head()

2)shape()

3)tail()

4describe()



In [50]:
#loading iris dataset directly form kaggle to google colaboratory
!pip install kaggle

In [51]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"jagdishchavan","key":"d11bb15abaf37f3a100817cf93c35787"}'}

In [52]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

#change the permission
!chmod 600 ~/.kaggle/kaggle.json

In [53]:
!kaggle datasets download -d uciml/iris

  0% 0.00/3.60k [00:00<?, ?B/s]
100% 3.60k/3.60k [00:00<00:00, 6.69MB/s]


In [54]:
from zipfile import ZipFile
file_name = "iris.zip"

with ZipFile(file_name,'r') as zip:
  zip.extractall()
  print('Done')

Done


In [55]:
#reading data from csv
iris = pd.read_csv('Iris.csv')

In [56]:
#to check first 5 rows in Data frame
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [57]:
#to check last 5 rows in Data frame
iris.tail()

Id  SepalLengthCm  ...  PetalWidthCm         Species
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[5 rows x 6 columns]

In [58]:
#to check rows and columns in Datasets
iris.shape

(150, 6)

In [59]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

#.iloc[ ] & loc[] Method
.iloc method will help us to extract rows and columns with respect to index

**SYNTAX**
df.iloc[row start:row stop, column start:column stop]

In [60]:
#e.g
iris.iloc[0:5,0:3]

Id  SepalLengthCm  SepalWidthCm
0   1            5.1           3.5
1   2            4.9           3.0
2   3            4.7           3.2
3   4            4.6           3.1
4   5            5.0           3.6

In [61]:
iris.loc[0:3,("PetalLengthCm",'PetalWidthCm')]

PetalLengthCm  PetalWidthCm
0            1.4           0.2
1            1.4           0.2
2            1.3           0.2
3            1.5           0.2

In [62]:
#DroppingColumns
iris.drop('SepalLengthCm',axis=1)

Id  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1           3.5            1.4           0.2     Iris-setosa
1      2           3.0            1.4           0.2     Iris-setosa
2      3           3.2            1.3           0.2     Iris-setosa
3      4           3.1            1.5           0.2     Iris-setosa
4      5           3.6            1.4           0.2     Iris-setosa
..   ...           ...            ...           ...             ...
145  146           3.0            5.2           2.3  Iris-virginica
146  147           2.5            5.0           1.9  Iris-virginica
147  148           3.0            5.2           2.0  Iris-virginica
148  149           3.4            5.4           2.3  Iris-virginica
149  150           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [64]:
#Drop Row
iris.drop([1,2,3],axis=0)

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
5      6            5.4  ...           0.4     Iris-setosa
6      7            4.6  ...           0.3     Iris-setosa
7      8            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[147 rows x 6 columns]

#Pandas Function

In [65]:
#Mean
iris.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [66]:
#minimum
iris.min()

Id                         1
SepalLengthCm            4.3
SepalWidthCm               2
PetalLengthCm              1
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object

In [67]:
#Median
iris.median()

Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [68]:
#Maximum
iris.max()

Id                          150
SepalLengthCm               7.9
SepalWidthCm                4.4
PetalLengthCm               6.9
PetalWidthCm                2.5
Species          Iris-virginica
dtype: object

In [69]:
#apply method
def half(s):
  return s*0.5

iris[['SepalLengthCm','PetalLengthCm']].apply(half)

SepalLengthCm  PetalLengthCm
0             2.55           0.70
1             2.45           0.70
2             2.35           0.65
3             2.30           0.75
4             2.50           0.70
..             ...            ...
145           3.35           2.60
146           3.15           2.50
147           3.25           2.60
148           3.10           2.70
149           2.95           2.55

[150 rows x 2 columns]

In [71]:
#value_Counts()
iris['Species'].value_counts()

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: Species, dtype: int64

In [72]:
iris.sort_values(by='SepalLengthCm')

Id  SepalLengthCm  ...  PetalWidthCm         Species
13    14            4.3  ...           0.1     Iris-setosa
42    43            4.4  ...           0.2     Iris-setosa
38    39            4.4  ...           0.2     Iris-setosa
8      9            4.4  ...           0.2     Iris-setosa
41    42            4.5  ...           0.3     Iris-setosa
..   ...            ...  ...           ...             ...
122  123            7.7  ...           2.0  Iris-virginica
118  119            7.7  ...           2.3  Iris-virginica
117  118            7.7  ...           2.2  Iris-virginica
135  136            7.7  ...           2.3  Iris-virginica
131  132            7.9  ...           2.0  Iris-virginica

[150 rows x 6 columns]